// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApiProject.Data;

#nullable disable

namespace LuANA_VICENTE.Migrations
{
    [DbContext(typeof(ConsumoContext))]
    partial class ConsumoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MinimalApiProject.Models.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConsumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("M3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorAgua")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Cpf", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
